# Numpy - Numerical Python

In [2]:
# importing the required library
import numpy as np

In [3]:
# Creating a 0D array

arr0 = np.array(2)
print(arr0)
print(type(arr0))
print("Dimension : ",arr0.ndim)

2
<class 'numpy.ndarray'>
Dimension :  0


In [4]:
# Creating a 1D array

arr = np.array([2,3,4,5,6])
print(arr)


[2 3 4 5 6]


In [5]:
print(type(arr))
print("Dimension : ",arr.ndim)

<class 'numpy.ndarray'>
Dimension :  1


In [6]:
arr_s = np.array(['a','b','c'])
print(arr_s)
print(type(arr_s))
print("Dimension : ",arr_s.ndim)

['a' 'b' 'c']
<class 'numpy.ndarray'>
Dimension :  1


In [7]:
# Creating a 2D Array

arr2 = np.array([[2,3,4,5,6],[7,8,9,10,11],[12,13,14,15,16]])
print(arr2)
print(type(arr2))
print("Dimension : ",arr2.ndim)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]
<class 'numpy.ndarray'>
Dimension :  2


In [8]:
# Creating a 3D Array

arr3 = np.array([[[2,3,4,5,6],[7,8,9,10,11],[12,13,14,15,16]],[[22,23,24,25,26],[27,28,29,30,11],[12,13,14,15,16]]])
print(arr3)
print(type(arr3))
print("Dimension : ",arr3.ndim)

[[[ 2  3  4  5  6]
  [ 7  8  9 10 11]
  [12 13 14 15 16]]

 [[22 23 24 25 26]
  [27 28 29 30 11]
  [12 13 14 15 16]]]
<class 'numpy.ndarray'>
Dimension :  3


In [9]:
# Creating a 5D Array

arr5 = np.array([2,3,4,5],ndmin=5)
print(arr5)
print(type(arr5))
print("Dimension : ",arr5.ndim)
      

[[[[[2 3 4 5]]]]]
<class 'numpy.ndarray'>
Dimension :  5


### Index and Slicing of Arrays

In [11]:
# indexing and slicing of a 1D array

arr

array([2, 3, 4, 5, 6])

In [12]:
arr[2]

4

In [13]:
arr[1:4]

array([3, 4, 5])

In [14]:
# step Slicing

arr[1:5:3]


array([3, 6])

In [15]:
arr[::4]

array([2, 6])

In [16]:
# indexing and slicing of a 2D array

arr2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [17]:
arr2[1,1]

8

In [18]:
arr2[2,3]

15

In [19]:
arr2[0,4]

6

In [20]:
arr2[2,0]

12

In [21]:
arr2[0:2,2:4]

array([[ 4,  5],
       [ 9, 10]])

In [22]:
arr2[1:3,3:5]

array([[10, 11],
       [15, 16]])

In [23]:
arr2[1:2,:]

array([[ 7,  8,  9, 10, 11]])

In [24]:
arr2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [25]:
arr2[:,1:4:2]

array([[ 3,  5],
       [ 8, 10],
       [13, 15]])

In [28]:
arr2[0:2,0:3:]

array([[2, 3, 4],
       [7, 8, 9]])

In [30]:
arr2[::2,:4:3]

array([[ 2,  5],
       [12, 15]])

#### Negative Indexing and Slicing 

In [40]:
arr

array([2, 3, 4, 5, 6])

In [44]:
arr[-1]

6

In [46]:
arr[-3:-1]

array([4, 5])

In [48]:
# checking for data types in an array

arr.dtype

dtype('int32')

In [50]:
arr_s = np.array(['a','b','c',])
arr_s.dtype

dtype('<U1')

In [60]:
# Changing data types

arr_float = arr.astype('f')
arr_float

array([2., 3., 4., 5., 6.], dtype=float32)

In [62]:
# Numpy Copy vs view

arr_c = arr.copy()
arr_v = arr.view()

In [64]:
print(arr)
print(arr_c)
print(arr_v)

[2 3 4 5 6]
[2 3 4 5 6]
[2 3 4 5 6]


In [66]:
arr[2] = 10

In [68]:
print(arr)
print(arr_c)
print(arr_v)

[ 2  3 10  5  6]
[2 3 4 5 6]
[ 2  3 10  5  6]


In [70]:
# Returning the shape of an array

arr.shape

(5,)

In [72]:
arr2.shape

(3, 5)

In [74]:
arr3.shape

(2, 3, 5)

In [76]:
# Array Reshaping 

arr2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [80]:
arr_22 = arr2.reshape(5,3)
arr_22

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [82]:
arr_22 = arr2.reshape(15,1)
arr_22

array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [84]:
arr3

array([[[ 2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16]],

       [[22, 23, 24, 25, 26],
        [27, 28, 29, 30, 11],
        [12, 13, 14, 15, 16]]])

In [86]:
arr3.reshape(10,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [11, 12, 13],
       [14, 15, 16]])

In [88]:
# Flattening of array

arr3.reshape(-1)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 11, 12, 13, 14, 15, 16])

In [94]:
# Numpy Array iteration 

for i in arr:
    print(i,end=" ")

2 3 10 5 6 

In [98]:
for i in arr2:
    for j in i:
        print(j,end=" ")

2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

In [102]:
for i in arr3:
    for j in i:
        for k in j:
            print(k,end=" ")

2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 22 23 24 25 26 27 28 29 30 11 12 13 14 15 16 

In [104]:
# nditer method

for i in np.nditer(arr3):
    print(i,end=" ")

2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 22 23 24 25 26 27 28 29 30 11 12 13 14 15 16 

In [106]:
arr_s

array(['a', 'b', 'c'], dtype='<U1')

In [116]:
for n,i in np.ndenumerate(arr_s):
    print(f"{n[0]} : {i}")

0 : a
1 : b
2 : c
