# Numpy - Numerical Python

In [2]:
# importing the required library
import numpy as np

In [12]:
# Creating a 0D array

arr0 = np.array(2)
print(arr0)
print(type(arr0))
print("Dimension : ",arr0.ndim)

2
<class 'numpy.ndarray'>
Dimension :  0


In [4]:
# Creating a 1D array

arr = np.array([2,3,4,5,6])
print(arr)


[2 3 4 5 6]


In [7]:
print(type(arr))
print("Dimension : ",arr.ndim)

<class 'numpy.ndarray'>
Dimension :  1


In [8]:
arr_s = np.array(['a','b','c'])
print(arr_s)
print(type(arr_s))
print("Dimension : ",arr_s.ndim)

['a' 'b' 'c']
<class 'numpy.ndarray'>
Dimension :  1


In [14]:
# Creating a 2D Array

arr2 = np.array([[2,3,4,5,6],[7,8,9,10,11],[12,13,14,15,16]])
print(arr2)
print(type(arr2))
print("Dimension : ",arr2.ndim)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]
<class 'numpy.ndarray'>
Dimension :  2


In [13]:
# Creating a 3D Array

arr3 = np.array([[[2,3,4,5,6],[7,8,9,10,11],[12,13,14,15,16]],[[22,23,24,25,26],[27,28,29,30,11],[12,13,14,15,16]]])
print(arr3)
print(type(arr3))
print("Dimension : ",arr3.ndim)

[[[ 2  3  4  5  6]
  [ 7  8  9 10 11]
  [12 13 14 15 16]]

 [[22 23 24 25 26]
  [27 28 29 30 11]
  [12 13 14 15 16]]]
<class 'numpy.ndarray'>
Dimension :  3


In [15]:
# Creating a 5D Array

arr5 = np.array([2,3,4,5],ndmin=5)
print(arr5)
print(type(arr5))
print("Dimension : ",arr5.ndim)
      

[[[[[2 3 4 5]]]]]
<class 'numpy.ndarray'>
Dimension :  5


### Index and Slicing of Arrays

In [16]:
# indexing and slicing of a 1D array

arr

array([2, 3, 4, 5, 6])

In [17]:
arr[2]

4

In [18]:
arr[1:4]

array([3, 4, 5])

In [39]:
# step Slicing

arr[1:5:3]


array([3, 6])

In [40]:
arr[::4]

array([2, 6])

In [19]:
# indexing and slicing of a 2D array

arr2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [21]:
arr2[1,1]

8

In [23]:
arr2[2,3]

15

In [24]:
arr2[0,4]

6

In [25]:
arr2[2,0]

12

In [28]:
arr2[0:2,2:4]

array([[ 4,  5],
       [ 9, 10]])

In [31]:
arr2[1:3,3:5]

array([[10, 11],
       [15, 16]])

In [34]:
arr2[1:2,:]

array([[ 7,  8,  9, 10, 11]])

In [41]:
arr2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [42]:
arr2[:,1:4:2]

array([[ 3,  5],
       [ 8, 10],
       [13, 15]])

In [46]:
arr2[0:2,0:3:2]

array([[2, 4],
       [7, 9]])

In [45]:
arr2[::2,:4:3]

array([[ 2,  5],
       [12, 15]])

In [48]:
# indexing and slicing of a 3D array

arr3

array([[[ 2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16]],

       [[22, 23, 24, 25, 26],
        [27, 28, 29, 30, 11],
        [12, 13, 14, 15, 16]]])

In [50]:
arr3[0,1,3]

10

In [53]:
arr3[1,1,1]

28

In [54]:
arr3[:,:,1:4:2]

array([[[ 3,  5],
        [ 8, 10],
        [13, 15]],

       [[23, 25],
        [28, 30],
        [13, 15]]])

In [55]:
arr3[:,1:3,1:3]

array([[[ 8,  9],
        [13, 14]],

       [[28, 29],
        [13, 14]]])

In [56]:
arr3

array([[[ 2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16]],

       [[22, 23, 24, 25, 26],
        [27, 28, 29, 30, 11],
        [12, 13, 14, 15, 16]]])

In [63]:
arr3[1,0:3:2,0:4:3]

array([[22, 25],
       [12, 15]])