## Numerical Python - Numpy

In [2]:
# Importing numpy as np

import numpy as np

In [3]:
# Creating a 0D Array

arr0 = np.array(5)
print(arr0)
print(type(arr0))
print("Dimension : ",arr0.ndim)

5
<class 'numpy.ndarray'>
Dimension :  0


In [4]:
# Creating a 1D Array

arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print("Dimension : ",arr1.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
Dimension :  1


In [5]:
# Creating a 2D Array

arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2)
print(type(arr2))
print("Dimension : ",arr2.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
Dimension :  2


In [6]:
# Creating a 3D Array

arr3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print(arr3)
print(type(arr3))
print("Dimension : ",arr3.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
<class 'numpy.ndarray'>
Dimension :  3


## Indexing and Slicing 

In [8]:
# Indexing in 1D Array

print(arr1[3])

4


In [9]:
# Indexing in 2D Array

print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
print(arr2[2,2])

11


In [11]:
print(arr2[1,3])

8


In [12]:
# Slicing in 2D Array

print(arr2[0:3,1:3])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [13]:
print(arr2[0:3,2:4])

[[ 3  4]
 [ 7  8]
 [11 12]]


In [14]:
# Step-Slicing in 2D Array

print(arr2[0:3,0:3:2])

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [15]:
print(arr2[0:3,1:4:2])

[[ 2  4]
 [ 6  8]
 [10 12]]


In [16]:
print(arr2[1:2,1:3:2])

[[6]]


In [17]:
# Indexing in 3D Array

print(arr3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [18]:
print(arr3[0,1,3])

8


In [19]:
print(arr3[0:1,1:2,3:4])

[[[8]]]


In [20]:
# Slicing in 3D Array

print(arr3[0:2,1:3,1:3])

[[[ 6  7]
  [10 11]]

 [[18 19]
  [22 23]]]


In [21]:
print(arr3[1:2,0:3,1:4])

[[[14 15 16]
  [18 19 20]
  [22 23 24]]]


In [22]:
# Step-Slicing in 3D Array

print(arr3[0:2,0:2,1:4:2])

[[[ 2  4]
  [ 6  8]]

 [[14 16]
  [18 20]]]


In [23]:
# Negative Indexing

print(arr1[-1])

4


In [24]:
print(arr1[-3:-1])


[2 3]


In [25]:
print(arr2[0:2,-3:-1])


[[2 3]
 [6 7]]


In [26]:
print(arr2[1:3,-5:-1:2])


[[ 5  7]
 [ 9 11]]


In [27]:
print(arr3[0:1,0:3,-3:-1])

[[[ 2  3]
  [ 6  7]
  [10 11]]]


In [28]:
# To check the Datatype

arr1.dtype

dtype('int32')

In [29]:
arr2.dtype

dtype('int32')

In [30]:
# Changing datatype

arr_string = arr1.astype('S')
arr_string


array([b'1', b'2', b'3', b'4'], dtype='|S11')

In [31]:
arr_float = arr2.astype('f')
arr_float

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)

In [32]:
# Copy and View

arr_c = arr1.copy()
print(arr_c)

[1 2 3 4]


In [33]:
arr_c = arr2.copy()
print(arr_c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
arr1.view()

array([1, 2, 3, 4])

In [35]:
arr2.view()

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
arr3.view()

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [37]:
#Returning the shape the of an Array

arr1.shape


(4,)

In [38]:
arr2.shape

(3, 4)

In [39]:
arr3.shape


(2, 3, 4)

In [40]:
# Reshaping an Array

arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
ary = arr2.reshape(1,12)
ary


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [42]:
ark = arr2.reshape(2,6)
ark

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [43]:
abb = arr3.reshape(3,4,2)
abb


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [44]:
# Negative Reshaping

asx = arr3.reshape(-1)
asx


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [45]:
# Numpy Array Interation

arr1.view()

array([1, 2, 3, 4])

In [46]:
for i in arr1:
    print(i,end=' ')

1 2 3 4 

In [47]:
for i in arr2:
    for j in i:
        print(j,end=' ')



1 2 3 4 5 6 7 8 9 10 11 12 

In [48]:
for i in arr3:
    for j in i:
        for k in j:
            print(k,end=' ')



1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 

## Numpy Joining Arrays


In [50]:
arr00 = np.array([12,14,16,18,20])
print(arr00)
arr01 = np.array([5,8,3,9,6])
print(arr01)

[12 14 16 18 20]
[5 8 3 9 6]


In [51]:
arry_join = np.concatenate([arr00,arr01])
arry_join


array([12, 14, 16, 18, 20,  5,  8,  3,  9,  6])

In [52]:
arry0 = np.array([[1,2,3,4],[5,6,7,8]])
arry1 = np.array([[10,11,12,13],[14,15,16,17]])
print(arry0)
print(arry1)


[[1 2 3 4]
 [5 6 7 8]]
[[10 11 12 13]
 [14 15 16 17]]


In [53]:
ary_join = np.concatenate([arry0,arry1])
ary_join

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [54]:
aroy0 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(aroy0)
aroy1 = np.array([[[99,98,97],[96,95,94]],[[93,92,91],[90,89,88]]])
print(aroy1)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[99 98 97]
  [96 95 94]]

 [[93 92 91]
  [90 89 88]]]


In [55]:
array_join = np.concatenate([aroy0,aroy1])
array_join


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[99, 98, 97],
        [96, 95, 94]],

       [[93, 92, 91],
        [90, 89, 88]]])

# Stacking in Numpy

In [57]:
arr_stack = np.stack([arr00,arr01],axis=1)
arr_stack

array([[12,  5],
       [14,  8],
       [16,  3],
       [18,  9],
       [20,  6]])

In [58]:
ar_stack = np.stack([arry0,arry1],axis=1)
ar_stack


array([[[ 1,  2,  3,  4],
        [10, 11, 12, 13]],

       [[ 5,  6,  7,  8],
        [14, 15, 16, 17]]])

In [118]:
print(arry0)
print(arry1)
ar_stack = np.hstack([arry0,arry1])
ar_stack

[[1 2 3 4]
 [5 6 7 8]]
[[10 11 12 13]
 [14 15 16 17]]


array([[ 1,  2,  3,  4, 10, 11, 12, 13],
       [ 5,  6,  7,  8, 14, 15, 16, 17]])

In [122]:
ar_stack = np.vstack([arry0,arry1])
ar_stack

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [124]:
ar_stack = np.dstack([arry0,arry1])
ar_stack

array([[[ 1, 10],
        [ 2, 11],
        [ 3, 12],
        [ 4, 13]],

       [[ 5, 14],
        [ 6, 15],
        [ 7, 16],
        [ 8, 17]]])

### Numpy array splitting

In [127]:
arr = np.arange(20)
arr



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [131]:
arr_split = np.array_split(arr,7)
arr_split


[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11]),
 array([12, 13, 14]),
 array([15, 16, 17]),
 array([18, 19])]

In [141]:
arr_split = np.hsplit(arr,5)
arr_split

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15]),
 array([16, 17, 18, 19])]

In [145]:
arr_2 = arr.reshape(2,10)
arr_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [147]:
arr2_splitt = np.vsplit(arr_2,2)
arr2_splitt

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [151]:
arr3 = arr.reshape(2,5,2)

arr3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [155]:
arr3_split = np.dsplit(arr3,2)
arr3_split

[array([[[ 0],
         [ 2],
         [ 4],
         [ 6],
         [ 8]],
 
        [[10],
         [12],
         [14],
         [16],
         [18]]]),
 array([[[ 1],
         [ 3],
         [ 5],
         [ 7],
         [ 9]],
 
        [[11],
         [13],
         [15],
         [17],
         [19]]])]

## Numpy array searching

In [158]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [160]:
np.where(arr%2==0,'Even','Odd')


array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even', 'Odd'], dtype='<U4')

In [166]:
np.where((arr>2) & (arr<10))

(array([3, 4, 5, 6, 7, 8, 9], dtype=int64),)

### Numpy Sorting

In [179]:
arr_sort = np.sort(arr)
print(arr_sort)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [181]:
# Searchsorted

np.searchsorted(arr,10)


10

### Numpy Filtering

In [183]:
# Numpy filterring array

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [189]:
Even_index = arr%2==0

In [191]:
arr[Even_index]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])