In [1]:
from numpy import random

In [2]:
x = random.randint(50,100)
x

69

In [3]:
y = random.rand()
y

0.31824091965183

In [4]:
# Creating a 1D array using random module
arr1 = random.randint(1,11,size=(10,))
arr1

array([ 3,  4,  8,  2,  4, 10,  3,  7,  6,  2])

In [5]:
# Creating a 2D array using random module
arr2 = random.randint(1,11,size=(3,2))
arr2


array([[4, 2],
       [4, 1],
       [1, 7]])

In [6]:
# Creating a 3D array using random module
arr3 = random.randint(1,11,size=(2,3,2))
arr3

array([[[ 8,  7],
        [ 7,  6],
        [10,  9]],

       [[ 3,  5],
        [ 7,  1],
        [ 6,  6]]])

In [7]:
# Creating a 1D array using random module
arr1 = random.rand(10,)
arr1

array([0.69123819, 0.2148059 , 0.73930715, 0.03997038, 0.09574008,
       0.03360014, 0.20719173, 0.29828955, 0.24805352, 0.21711278])

In [8]:
# Creating a 2D array using random module
arr1 = random.rand(4,3)
arr1

array([[0.97190553, 0.87789375, 0.30543542],
       [0.0835134 , 0.9568612 , 0.69034547],
       [0.60697349, 0.4057304 , 0.0938333 ],
       [0.67118959, 0.21706717, 0.01792138]])

In [9]:
# Choice

arr_c = random.choice([4,7,8,2],size=(4,2))
arr_c

array([[4, 4],
       [4, 7],
       [8, 4],
       [7, 8]])

In [10]:
arr_c = random.choice([4,7,8,2],p=[0.8,0.05,0.05,0.1],size=(4,2))
arr_c

array([[4, 4],
       [4, 4],
       [4, 4],
       [4, 4]])

In [11]:
arr2

array([[4, 2],
       [4, 1],
       [1, 7]])

In [12]:
random.shuffle(arr2)
arr2


array([[1, 7],
       [4, 1],
       [4, 2]])

In [13]:
print(arr1)
arr_p = random.permutation(arr1)
arr_p

[[0.97190553 0.87789375 0.30543542]
 [0.0835134  0.9568612  0.69034547]
 [0.60697349 0.4057304  0.0938333 ]
 [0.67118959 0.21706717 0.01792138]]


array([[0.0835134 , 0.9568612 , 0.69034547],
       [0.60697349, 0.4057304 , 0.0938333 ],
       [0.97190553, 0.87789375, 0.30543542],
       [0.67118959, 0.21706717, 0.01792138]])

# Numpy Universal FUNCTIONS

In [2]:
import numpy as np

In [4]:
def add(a,b):
    return a+b

print(type(add))

<class 'function'>


In [6]:
print(type(np.add))

<class 'numpy.ufunc'>


In [8]:
add_u = np.frompyfunc(add,2,1)
print(type(add_u))

<class 'numpy.ufunc'>


In [16]:
# add
arr1 = np.array([2,3,4,5])
arr2 = np.array([4,5,6,7])

arr3 = np.add(arr1,arr2)
arr3

array([ 6,  8, 10, 12])

In [18]:
# subtract
arr1 = np.array([2,3,4,5])
arr2 = np.array([4,5,6,7])

arr3 = np.subtract(arr1,arr2)
arr3

array([-2, -2, -2, -2])

In [22]:
# mulitply
arr1 = np.array([2,3,4,5])
arr2 = np.array([4,5,6,7])

arr3 = np.multiply(arr1,arr2)
arr3

array([ 8, 15, 24, 35])

In [28]:
# mod
arr1 = np.array([2,3,4,5])
arr2 = np.array([4,5,6,7])

arr3 = np.remainder(arr2,arr1)
arr3

array([0, 2, 2, 2])

In [30]:
# divmod
arr1 = np.array([2,3,4,5])
arr2 = np.array([4,5,6,7])

arr3 = np.divmod(arr2,arr1)
arr3

(array([2, 1, 1, 1]), array([0, 2, 2, 2]))

In [32]:
# absolute
arr1 = np.array([2,-3,4,-5])
# arr2 = np.array([4,5,6,7])

arr3 = np.abs(arr1)
arr3

array([2, 3, 4, 5])

### Numpy Logarithmic Fucntions

In [35]:
# log2

base = np.log2(arr1)
base

C:\Users\VICTUS\AppData\Local\Temp\ipykernel_9196\2525474654.py:3: RuntimeWarning: invalid value encountered in log2
  base = np.log2(arr1)


array([ 1., nan,  2., nan])

In [37]:
# log10
base = np.log10(arr1)
base

C:\Users\VICTUS\AppData\Local\Temp\ipykernel_9196\2932962257.py:1: RuntimeWarning: invalid value encountered in log10
  base = np.log10(arr1)


array([0.30103   ,        nan, 0.60205999,        nan])

In [39]:
# loge
base = np.log(arr1)
base

C:\Users\VICTUS\AppData\Local\Temp\ipykernel_9196\2075982791.py:1: RuntimeWarning: invalid value encountered in log
  base = np.log(arr1)


array([0.69314718,        nan, 1.38629436,        nan])

In [41]:
from math import log

In [43]:
print(type(log))

<class 'builtin_function_or_method'>


In [47]:
log_u = np.frompyfunc(log,2,1)
print(type(log_u))

<class 'numpy.ufunc'>


In [59]:
# log at any base
l
for i in arr2:
    print(log_u(i,20),end=" ")
    # print(i)

0.46275642631951835 0.5372435736804817 0.5981040045018439 0.6495607655709434 

In [63]:
# np.sum

arr1 = np.array([2,3,4,5])
arr2 = np.array([4,5,6,7])

# arr3 = np.sum([arr1,arr2])
# arr3

arr3 = np.sum([arr1,arr2],axis=1)
arr3

array([14, 22])

In [65]:
arr1 = np.array([2,3,4,5])

arr3 = np.cumsum(arr1)
arr3

array([ 2,  5,  9, 14])

In [71]:
# Product
arr1 = np.array([2,3,4,5])
arr2 = np.array([4,5,6,7])

arr3 = np.prod([arr1,arr2])
arr3

# arr3 = np.prod([arr1,arr2],axis=1)
# arr3

100800

In [73]:
arr1 = np.array([2,3,4,5])

arr3 = np.cumprod(arr1)
arr3

array([  2,   6,  24, 120])

In [79]:
# np.diff

arr1 = np.array([2,3,4,5])
# arr2 = np.array([4,5,6,7])

# arr3 = np.sum([arr1,arr2])
# arr3

arr3 = np.diff(arr1,n=2)
arr3

array([0, 0])

#### Trignometric Functions

In [82]:
values = [np.pi,np.pi/2,np.pi/3,np.pi/4]
print(values)

[3.141592653589793, 1.5707963267948966, 1.0471975511965976, 0.7853981633974483]


In [84]:
degrees = np.rad2deg(values)
degrees

array([180.,  90.,  60.,  45.])

In [86]:
sin_val = np.sin(values)
sin_val

array([1.22464680e-16, 1.00000000e+00, 8.66025404e-01, 7.07106781e-01])

In [88]:
cos_val = np.cos(values)
cos_val

array([-1.00000000e+00,  6.12323400e-17,  5.00000000e-01,  7.07106781e-01])

In [90]:
tan_val = np.tan(values)
tan_val

array([-1.22464680e-16,  1.63312394e+16,  1.73205081e+00,  1.00000000e+00])

In [92]:
# Inverse values

sin_val = np.arcsin(values)
sin_val

C:\Users\VICTUS\AppData\Local\Temp\ipykernel_9196\4222470800.py:3: RuntimeWarning: invalid value encountered in arcsin
  sin_val = np.arcsin(values)


array([       nan,        nan,        nan, 0.90333911])

In [94]:
cos_inv = np.arccos(values)
cos_inv

C:\Users\VICTUS\AppData\Local\Temp\ipykernel_9196\850971523.py:1: RuntimeWarning: invalid value encountered in arccos
  sin_val = np.arccos(values)


array([       nan,        nan,        nan, 0.66745722])

In [96]:
tan_inv = np.arctan(values)
tan_inv

array([1.26262726, 1.00388482, 0.80844879, 0.66577375])

In [98]:
# Hyperbolic Trignometric functions

# Hyperbolic sin values

sin_val = np.sinh(values)
sin_val

array([11.54873936,  2.3012989 ,  1.24936705,  0.86867096])

In [100]:
# Hyperbolic cos values

cos_val = np.cosh(values)
cos_val

array([11.59195328,  2.50917848,  1.60028686,  1.32460909])

In [102]:
# Inverse Hyperbolic sin values

sin_val = np.arcsinh(values)
sin_val

array([1.86229574, 1.23340312, 0.91435666, 0.72122549])

### Numpy Set Operations

In [105]:
arr1 = np.array([2,4,3,2,4,3,5])
arr2 = np.array([6,5,4,5,7,4,8])
arr1_u = np.unique(arr1)
arr1_u

array([2, 3, 4, 5])

In [107]:
# Union

arr_3 = np.union1d(arr1,arr2)
arr_3

array([2, 3, 4, 5, 6, 7, 8])

In [109]:
# Intersection
arr_3 = np.intersect1d(arr1,arr2)
arr_3

array([4, 5])

In [111]:
# Difference

arr_3 = np.setdiff1d(arr1,arr2)
arr_3

array([2, 3])

In [113]:
arr_3 = np.setdiff1d(arr2,arr1)
arr_3

array([6, 7, 8])

In [115]:
# Symmetric Difference

arr_3 = np.setxor1d(arr2,arr1)
arr_3

array([2, 3, 6, 7, 8])